version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: teamops_docker_db
      POSTGRES_USER: postgres_d
      POSTGRES_PASSWORD: admin_d
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: